services:
  hatsune-miku-bot:
    build: .
    image: hatsune-miku-bot
    container_name: hatsune-miku-bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
