name: Hatsune Miku Deploy

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}
          tags: tag:ci
